### ISSUE TITLE
[V1.13.0] Spinner infini après erreurs de saisie du code rncp

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#106]
Saisie puis effacement et ressaisie  : le système n'a pas aimé, effacement complet du champ impossible : 
![image](https://user-images.githubusercontent.com/63646363/149939558-2c8dd10c-6796-4058-b426-b3741396c21d.png)

Puis message de proposition d'attendre ou de quitter => choix quit et arrivée sur cet écran : 
![image](https://user-images.githubusercontent.com/63646363/149939789-a99b6ea4-03b9-470a-977b-c3bb4ad8dd7d.png)

**Comment by antoinebigard** [comment]
Le SNAP (aïe aïe ..) c'est lié à autre chose de plus important, il y a une fuite mémoire dans le formulaire, j'ai la même chose de temps à autre sur mon poste. je pense que si tu ouvres  puis referme les accordéons, utilises des champs et encore ouvres et refermes ls accordéon. Ouvrir des dossiers etc.. sans actualiser la page je pense que ça snap forcement.
c'est ma première prio après la livraison. 

En revanche, ton cas de RNCP est intéressant  ça ma permis de voir que je gérais pas les inactifs. 
Modif dans la PR attachée.
