### ISSUE TITLE
[v1.14.0] Empêcher la saisie de caractères numériques là où de l'alpha est attendu et inversement

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#111]
Champs commune et commune de naissance (bloc apprenti) : 

![image](https://user-images.githubusercontent.com/63646363/149959898-1e135fa3-7e7b-49dd-be97-3377c340b48b.png)

Champs  Nom et Prénom (bloc apprenti et bloc maitre d'apprentissage) : 

![image](https://user-images.githubusercontent.com/63646363/149960013-738ed1d5-85e2-48bd-bf58-059111d8c8f6.png)

IDCC

=> + positionner messages d'erreur explicites de type  : ce champ doit être renseigné en lettres / ce champ doit être renseigné en chiffres

**Comment by antoinebigard** [comment]
Ok pour Nom, prénom.


Pas ok pour Commune., exemple : 
```
{
    "code_postal": "75002",
    "code_commune_insee": "75102",
    "commune": "Paris 2e Arrondissement",
    "num_departement": "75",
    "nom_departement": "Paris",
    "region": "Île-de-France",
    "num_region": "11",
    "nom_academie": "Paris",
    "num_academie": 1
}
```


Reste :
IDCC
Message d'erreur
