### ISSUE TITLE
[v1.14.0-beta.3] Régression : smic mahorais non pris en compte

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#129]
test avec lieu d'habitation apprenti 97600 Koungou : 

![image](https://user-images.githubusercontent.com/63646363/150154357-7e83a051-435e-4669-8f3a-db3f937d0afb.png)

**Comment by antoinebigard** [comment]
Je pense que c'est lié au rafraîchissement du département. mais effectivement j'aurais besoin de ton process pour comprendre la combinaison.


super pour faire des gif screenshot en 2 secondes 
[zappy](https://zapier.com/zappy)

**Comment by Anne-Camille** [comment]
merci pour l'outil ; je ne suis pas sous mac, je vais essayer d'un trouver un compatible windows donc en attendant voici les étapes : 
étape 1. saisie d'un code postal métropolitain
étape 2. saisie d'autres éléments (dates etc)
étape 3. bloc rému OK
étape 4. retour sur bloc apprenti et modification du code postal de résidence par un code postal mahorais
étape 5. bloc rému pas actualisé.

Il semble que le bloc rému ne soit jamais réactualisé suite à modification du bloc apprenti, sur le code postal mais aussi sur l'âge par ex (qui modifierait les % de smic).
