### ISSUE TITLE
v1.14.0-beta.4 - Faire apparaître la mention sur la conservation des données au même endroit que la certification d'exactitude

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#132]
CGU et évenuellement au niveau de la coche "je m'engage à vérifier l'exactitude des éléments transmis"

« Pendant la durée du contrat d’apprentissage, et après son terme, il peut vous être demandé de fournir l’original du contrat signé, les pièces permettant d’attester du respect des déclarations figurant dans le contrat d’apprentissage ainsi que la convention de formation, et le cas échéant la convention tripartite. Il vous appartient donc de conserver l’ensemble de ces documents originaux. »
Note : lien CGU footer cassé

https://github.com/mission-apprentissage/cerfa/issues/295

@christophebonraisin PI

**Comment by Anne-Camille** [comment]
@pabloHry il faut ajouter la phrase suivante : Pendant la durée du contrat d’apprentissage, et après son terme, il peut vous être demandé de fournir l’original du contrat signé, les pièces permettant d’attester du respect des déclarations figurant dans le contrat d’apprentissage ainsi que la convention de formation, et le cas échéant la convention tripartite. Il vous appartient donc à conserver l’ensemble de ces documents originaux. 

ici : 
![image](https://user-images.githubusercontent.com/63646363/153175885-7b79760b-c28e-4966-aceb-34fffcce5e2a.png)

pour le lien CGU oui a priori rétabli.

**Comment by pabloHry** [comment]
merci
