### ISSUE TITLE
[v1.14.0-beta.5] formation pas à 100% malgré tous les champs remplis

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#137]
![image](https://user-images.githubusercontent.com/63646363/150361555-ce0e7d38-4956-4d61-a9b3-71be5ef4611f.png)

**Comment by antoinebigard** [comment]
**Retour de Farid Souiah:**

Lors de la recette de la saisie d’un contrat,

Je suis bloqué au BLOC FORMATION à 92% alors que tous les champs sont validés ?

Est-ce une erreur de ma part ?

![image002](https://user-images.githubusercontent.com/6003532/150416403-ab61d46f-e55e-4f5b-9271-49b3e24dd571.png)

**Comment by antoinebigard** [comment]
Bug reproduit, confirmé et corrigé.

L'uai saisit à la main n'était pas enregistré en base.
