### ISSUE TITLE
Bloc rémunération - avantages en nature : vérifier que la possibilité de mettre “,” ou “.” pour signifier la décimale n'a pas d'incidence.

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#175]
Simple vérification du format d'échange car aujourd'hui, il est possible de renseigner un montant avec deux types de caractères pour la décimale.

**Comment by Anne-Camille** [comment]
@flodlc je te quote sur cette carte, au cas où tu pourrais vérifier ce point (virgule ! )

**Comment by flodlc** [comment]
> @flodlc je te quote sur cette carte, au cas où tu pourrais vérifier ce point (virgule ! )

La virgule est maintenant autorisée mais instantanément remplacée par un point. 
Et seules les points sont ensuite conservés dans notre data.
