### ISSUE TITLE
Wording messages erreur 

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#190]
- [ ] Revue des messages d'erreur dans [ce doc](https://docs.google.com/spreadsheets/d/1-qdInJeYmqjI1DVdazWwtD_8Tb2aCRQZ40TuDYKZlBw/edit#gid=0) en colonne E (attention différents onglets)

**Comment by ClemLan** [comment]
@Anne-Camille c'était bon ça non ?

**Comment by Anne-Camille** [comment]
@ClemLan je sais que j'avais commencé à rédiger des trucs mais je ne sais pas si tu avais complété le reste, si tout est ok ?

**Comment by ClemLan** [comment]
@Anne-Camille j'avais complété un peu oui

**Comment by Anne-Camille** [comment]
ok nickel @ClemLan ! du coup, y a-t-il moyen de mettre en com sur la maquette côté statut en erreur le lien vers le doc ?
je pense qu'il manque les wordings warning du coup.

**Comment by ClemLan** [comment]
@Anne-Camille done
