### ISSUE TITLE
[Abandon]  Ux Flow : Déplacer les champs type de contrat + date début + date de fin de contrat afin de déduire tous les contrôles de date (naissance apprenti, naissance maitre apprentissage...)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#196]
Abandon, doublon avec https://github.com/mission-apprentissage/cerfa/issues/178

A conforter : un test utilisateur a montré une grande facilité à saisir les éléments et à retrouver les champs concernés du fait de l'habitude de l'utilisateur du cerfa papier.  Le fait que le formulaire soit identique au papier a facilité la complétude.

Retour par mail (Mme Simonot DGFIP : Le remplissage du CERFA en ligne suit l'ordre chronologique du CERFA papier. On voit les différentes étapes, c'est pratique et clair.

2 parcours ? 1 classique pour les rois du cerfa, 1 conversationnel pour les débutants du cerfa ?

**Comment by ClemLan** [comment]
@acm est-ce qu'on cloture cette card ? il me semble qu'on avait décidé de ne rien bouger puisque de cette manière ils s'y retrouvaient plus facilement et qu'on avait mis d'autres choses en place depuis ?
