### ISSUE TITLE
[Corrections Design]

### ISSUE THREAD

**Issue by ClemLan** [mission-apprentissage/cerfa#234]
- [x] Le chevron pour fermer la colonne "menu" à gauche devrait comporter une stroke appuyée sur le séparateur afin de bien montrer leur lien (i.e. "fermer/ouvrir le menu")
https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=555%3A57631

- [x] passer l'écart des boutons primaires et secondaires de 10px à 16px
https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=471%3A46662

- [x] Dans le champ du formulaire "Code IDCC de la convention collective" le label devrait indiquer "9999 - Sans convention collective" (pour que l'utilisateur ne se pose pas de question)
<img width="539" alt="Capture d’écran 2022-02-03 à 12 23 29" src="https://user-images.githubusercontent.com/73469494/152333889-4473c2df-a8a2-43f6-aa33-1cd8e4cf455d.png">

- [x] N° SIRET : mettre la description "les informations seront automatiquement complétées à partir du N° Siret"

- [x] Vérifier la marge en dessous du champ -> devrait être à 32px (si c'est le cas, passer à 64px)
https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=615%3A66688

- [ ] Mon compte > Mes informations : corriger les fautes d'orthographe (voir commentaire 58)
https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=615%3A66691

**Comment by antoinebigard** [comment]
A re-discuter
