### ISSUE TITLE
Intégrer Logos plan de relance suite financement ITN

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#238]
Suite recette 

- [ ] enlever pointeur icon sur image
- [ ] diminuer les margin top et bottom

Les conventions ITN, par lesquelles nous sommes financés prévoient l’intégration sur les sites  des logos de France relance et du plan européen
=> faire apparaître les logos sur le front
https://www.economie.gouv.fr/files/files/directions_services/plan-de-relance/etiquette_France_Relance_UE.png
[Lien vers kit com](https://www.economie.gouv.fr/plan-de-relance/kit-de-communication#)

**Comment by ClemLan** [comment]
A cet emplacement ça vous convient ? 
(J'ai croppé un peu pour lui faire prendre le plus d'importance sans modifier la height du footer)
https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=740%3A64431

**Comment by Anne-Camille** [comment]
@ClemLan Perfect merci !
