### ISSUE TITLE
Rendre optionnel le n° de contrat précédent pour les contrats de type 2x

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#240]
on ne peut pas saisir un contrat de type succession (21, 22 ou 23) sans le numéro de contrat précédent :
                le fonctionnement attendu : le numéro de contrat précédent est optionnel pour les contrats de type 2x
                le fonctionnement à date : le champ apparaît comme optionnel, mais en son absence, le % d’avancement n’arrive pas à 100% pour le bloc contrat

**Comment by antoinebigard** [comment]
https://cdn.zappy.app/4505180592365095d46c7b35d9b70644.mp4 non reproductible
