### ISSUE TITLE
Communiquer liste des statuts à l'Assistance

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#243]
Statuts avant télétransmission (sur Plateforme) avec explication : 

-  Brouillon : le dossier est en cours de création, statut attribué dès l'ouverture d'un nouveau contrat
- Dossier terminé : le dossier est complet : toutes les informations sont renseignées et comporte les pièces jointes le cas échéant. _(voir si à remplacer par télétransmis ou si créa d'un statut "télétransmis")_
- En attente d'action : le dossier a été envoyé pour signature électronique, il n'est pas encore signé
- ... ?

_Pour publication de liste ou info utilisateur sur la plateforme, ajouter les statuts Agecap et leur signification._

**Comment by antoinebigard** [comment]
## Mode d'un dossier : 
Les modes symbolisent les types de parcours possibles.
```
      "NOUVEAU_CONTRAT_SIGNATURE_ELECTRONIQUE", 
      "NOUVEAU_CONTRAT_SIGNATURE_PAPIER"
```

## Etat d'un dossier : 

### Les états symbolisent les "statuts possible"

```
// Plateforme
      "BROUILLON",
      "DOSSIER_FINALISE_EN_ATTENTE_ACTION", 

      "EN_ATTENTE_DECLENCHEMENT_SIGNATURES",
      "EN_ATTENTE_SIGNATURES", 
      "SIGNATURES_EN_COURS",
      "DOSSIER_TERMINE_AVEC_SIGNATURE", 

      "DOSSIER_TERMINE_SANS_SIGNATURE", 

// Envoi vers AGECAP
      "TRANSMIS", 

// AGECAP
      "EN_COURS_INSTRUCTION", 
      "INCOMPLET", 
      "DEPOSE", 
      "REFUSE", 

// Après dépôt DECA
      "ENGAGE", 
      "ANNULE", 
      "RUTPURE",
      "SOLDE", 
```

### Les différents états en "texte"
```javascript
const DOSSIER_STATUS = {
  BROUILLON: {
    text: "Brouillon",
  },
  DOSSIER_FINALISE_EN_ATTENTE_ACTION: {
    text: "Dossier finalisé en attente d'action",
  },
  EN_ATTENTE_DECLENCHEMENT_SIGNATURES: {
    text: "En attente d'action",
  },
  EN_ATTENTE_SIGNATURE: {
    text: "En attente de signature",
  },
  EN_ATTENTE_SIGNATURES: {
    text: "En attente de signatures",
  },
  SIGNATURES_EN_COURS: {
    text: "En cours de signatures",
  },
  SIGNE: {
    text: "Signé",
  },
  DOSSIER_TERMINE_AVEC_SIGNATURE: {
    text: "Dossier terminé",
  },
  DOSSIER_TERMINE_SANS_SIGNATURE: {
    text: "Dossier terminé",
  },
  TRANSMIS: {
    text: "Transmis",
  },
  EN_COURS_INSTRUCTION: {
    text: "En cours d'instruction",
  },
  INCOMPLET: {
    text: "Demande de complément",
  },
  DEPOSE: {
    text: "Déposé",
  },
  REFUSE: {
    text: "Refusé",
  },
  ENGAGE: {
    text: "Engagé",
  },
  ANNULE: {
    text: "Annulé",
  },
  RUTPURE: {
    text: "Rupture",
  },
  SOLDE: {
    text: "Soldé",
  },
};
```

### visuellement
![image](https://user-images.githubusercontent.com/6003532/152738464-62b87524-4a02-4215-bae8-e54bc812b2d8.png)


## Parcours possible : 

### Aucun mode et Tous mode (aller/retour)
Etat possible => 
"BROUILLON", "DOSSIER_FINALISE_EN_ATTENTE_ACTION", 


### mode NOUVEAU_CONTRAT_SIGNATURE_ELECTRONIQUE

Etat possible => 
      "EN_ATTENTE_DECLENCHEMENT_SIGNATURES",
      "EN_ATTENTE_SIGNATURES", 
      "SIGNATURES_EN_COURS",
      "DOSSIER_TERMINE_AVEC_SIGNATURE", 
      "DOSSIER_TERMINE_SANS_SIGNATURE", 

      "TRANSMIS", 

      "EN_COURS_INSTRUCTION", 
      "INCOMPLET", 
      "DEPOSE", 
      "REFUSE", 

      "ENGAGE", 
      "ANNULE", 
      "RUTPURE",
      "SOLDE", 
      
      
 ### mode NOUVEAU_CONTRAT_SIGNATURE_PAPIER

Etat possible => 
       "DOSSIER_TERMINE_SANS_SIGNATURE", 

      "TRANSMIS", 

      "EN_COURS_INSTRUCTION", 
      "INCOMPLET", 
      "DEPOSE", 
      "REFUSE", 

      "ENGAGE", 
      "ANNULE", 
      "RUTPURE",
      "SOLDE",

**Comment by Anne-Camille** [comment]
FAQ mise à jour avec les différents statuts + lien communiqué à l'assistance => done
