### ISSUE TITLE
Ajouter un texte au niveau du bloc rému : pour informer que les situations spécifiques ne sont pas prises en compte dans le calcul

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#245]
- [x] rédiger texte => acm
- [x] révision texte auprès de Noel C.=> mail envoyé le 07/02
- [x] intégrer texte => clémence si besoin design + pablo

Le calcul de rémunération proposé par la plateforme : 

- indique la rémunération minimale légale, l'employeur pouvant décider d'attribuer une rémunération plus avantageuse

- ne tient pas encore compte de situations spécifiques (exemples : rémunération du contrat d'apprentissage préparant à une licence professionnelle, majorations règlementaires, apprentis ayant une reconnaissance de travailleur handicapé). En savoir plus sur les situations spécifiques sur [le site du Ministère du Travail, de l'Emploi et de l'Insertion](https://travail-emploi.gouv.fr/formation-professionnelle/formation-en-alternance-10751/apprentissage/contrat-apprentissage#salaire).

🦠ouverture du lien dans un nouvel onglet + ajout de l'icône : 
![image](https://user-images.githubusercontent.com/63646363/153853373-28f049a8-0538-4632-8a34-d1529f30eebe.png)

**Comment by pabloHry** [comment]
Je pense que je vais attendre ton beau figma ^^ @ClemLan

**Comment by Anne-Camille** [comment]
@ClemLan nice, merci !
@pabloHry cette carte est ultra prio par rapport aux autres !
