### ISSUE TITLE
Ui / Gérer les différents états des champs à remplir

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#252]
Gérer les différents statuts des champs en visuel : 

- [x] inactif /disabled
- [x] non rempli
- [x] en cours de sauvegarde
- [ ] sauvegardé
- [x] en chargement (appel API en cours)
- [x] autocomplété avec succès
- [x] Erreur :  mauvais format de données, donnée invalide, incohérence des données saisies, champ vide
- [x] Attention : siret secret défense ou API HS ou autres à définir 

1. donnée pré-remplie et précomplétée : aujourd'hui, mise en vert + coche lorsque le champ est rempli, demain message de validation
2. donnée en erreur (vide ou pb de format)  : lien avec [highlight des champs](https://github.com/mission-apprentissage/cerfa/issues/165) ; lien avec [messages d'erreur apparaissant pendant la saisie ](https://github.com/mission-apprentissage/cerfa/issues/253)
3. attention (siret secret ou API HS : info "données non récupérables automatiquement)
4. donnée pré-enregistrée en base de donnée (si on revient sur le dossier, la donnée est encore présente) : aujourd'hui, mise en vert + coche lorsque le champ est rempli

**Comment by ClemLan** [comment]
@Anne-Camille 
1. Dans le cas du SIRET : loader + ajout message de validation
https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=846%3A88508

2. Voir les renvois (+ ne pas afficher le message d'erreur tant que la saisie n'est pas remplie-.

3. /

4. Ne pas afficher la coche verte, qui n'est pas très affordante pour l'utilisateur : laisse penser que l'information est bonne (et pas son format ou son enregistrement).  
L'enregistrement sera rendu (un peu) plus évident avec le bouton stick (+ visuels à venir). 
Il peut également prendre la forme d'un loader/changement d'état dans le tag "enregistrement auto"

**Comment by Anne-Camille** [comment]
@ClemLan ok pour moi. Je fais un nouveau doc pour reprendre les corrections à apporter suite à la mep de ce jour.

**Comment by ClemLan** [comment]
@Anne-Camille j'ai fait une petite modification, sur quel doc mets-tu les corrections ?

**Comment by Anne-Camille** [comment]
ici : https://docs.google.com/spreadsheets/d/1uALGD7ejKgvRAg9R4yNt8lupFhisFLw2PDIMxsO3R5A/edit?usp=sharing

J'ai commencé à compléter la partie employeur : en grisé, tout ce qui est déjà traité / en visu / sans info
 ; et en bleu tout ce qui doit être ajouté/modifié/supprimé

**Comment by ClemLan** [comment]
DSFR (avec modifs) : https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=876%3A93117

Recos CERFA https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=876%3A96467

@Anne-Camille @antoinebigard on pourra rediscuter de la sauvegarde si vous voulez

**Comment by ClemLan** [comment]
@Anne-Camille pour review

Après discussion sur la sauvegarde : loader temporaire dans le champ + modale de sortie :   https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=910%3A72549

SIRET : https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=876%3A96467

DSFR avec modifs : https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=876%3A93117
