### ISSUE TITLE
Tableau de dossier Mon espace (V1 avec Ui)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#254]
Suite de la V0 : https://github.com/mission-apprentissage/cerfa/issues/99

En tant qu'utilisateur, je dois voir les informations qui me permettent de repérer un dossier dans la liste pour le sélectionner facilement.
- [x] définir quelles sont les infos non utiles à ce stade et les retirer / lesquelles sont absolument nécessaires et à maintenir ou ajouter 
- 1ers retours souhaité : nom | prénom apprenti | date début de contrat | statut du dossier ; 
- autres retours à confirmer : ajout n° télétransmission ? présence de PJ ?
- [x] définir quelles sont les infos de premier niveau, visibles dès l'arrivée sur l'écran liste de dossier et quelles sont les infos secondaires à mettre par ex en collapse (ou autre)
- [x] maquetter l'ensemble
- attention : les noms prénoms apprentis ne seront disponibles que lorsque l'utilisateur aura renseigné les champs : il peut exister un stade transitoire où ils ne sont pas encore connus ; idem n° de télétransmission qui ne sera connu que lorsque le doc est au stade terminé)
- la maquette devra prévoir le moyen d'informer l'utilisateur sur les éléments (ex : signification des différents statuts), une suggestion avait été faite sur une frise chronologique-repère  avec des pastilles reprises sur chacune des lignes du dossier pour visualiser l'étape du processus)

Tableau : [maquette](https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=1218%3A133029)

[Démo tri](https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=1441%3A130709)

[Zones de clic](https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=1441%3A131178)

V2 : https://github.com/mission-apprentissage/cerfa/issues/550

**Comment by ClemLan** [comment]
Première proposition : https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=761%3A66866

À mettre à jour avec : 
- [ ] confrontation équipe
- [ ] frise chronologique
- [ ] présence de PJ ?
- [ ] dernière modification ?

**Comment by ClemLan** [comment]
Lié à #99

**Comment by ClemLan** [comment]
@Anne-Camille je ne sais pas si ça a été mis dans la prod actuelle mais ce serait pas mal (surtout pour le nom de dossier et le tri)

**Comment by houssinegart** [comment]
une action est attendu de notre part sur ce sujet @rsauvair  ?

**Comment by rsauvair** [comment]
@houssinegart Pourrais-tu vérifier en environnement de recette que cela correspond bien à l'attendu stp ?
