### ISSUE TITLE
bug RNCP + intégrer le "RNCP" déjà rempli (puisque obligatoire)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#257]
Je saisis juste des chiffres => invalide 
J'efface ma sélection pour saisir un nouveau code => impossible

Proposition : mettre "RNCP" en dur et ne permettre que la saisie de chiffres dans le champs, pour éviter l'invalidité de la saisie, l'effacement et l'impossibilité de ressaisie.

**Comment by antoinebigard** [comment]
- [ ] Ajouter un Masque sur le champ RNCP . (RNCP____)
- [ ] Rendre possible le copier / coller d'un code peut importe ça forme "RNCP15016 ou 15016"
