### ISSUE TITLE
Info sur les rôles : ajout d'un lien vers la FAQ dans la popin partage de dossier (V1)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#282]
- [x] rédiger page de FAQ concernant les rôles=> clemence + acm
- [x] mettre lien vers FAQ ici =>https://contrat-recette.apprentissage.beta.gouv.fr/assistance/faq (pas d'ancre possible sur la partie spécifique)
- [x] wording lien + éventuellement design => clemence
- [x] positionner le lien dans la popin de partage => antoine ou pablo, selon maquette (sauf icone ouvrir nouvel onglet à mettre après le lien) :  https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=471%3A46910

Ceci est la V1 de https://github.com/mission-apprentissage/cerfa/issues/364

**Comment by ClemLan** [comment]
Propo : https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=471%3A46910
