### ISSUE TITLE
[Abandon]RTD Mettre en place nouvelle mire de connexion 50/50

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#283]
**Abandonné au profit de la 441**

https://github.com/mission-apprentissage/cerfa/issues/441

maj maquette avec les retours suivants : 
Remplacer s’identifier par le portail de services par « S’identifier via le portail Mes Démarches Emploi et Formation » 
Retirer la mention « si vous avez un compte(...) » 

_Assistance évoque "mes démarches" avec les utilisateurs ; le terme "portail de services" ne semble rien évoquer aux utilisateurs => à confirmer par d'autres tests U)_

maquette en commentaire

**Comment by ClemLan** [comment]
[https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=543%3A57840](url)

**Comment by Anne-Camille** [comment]
@antoinebigard pour avis

**Comment by ClemLan** [comment]
@Anne-Camille MAJ
