### ISSUE TITLE
Modifier la couleur des champs du CERFA vert => bleu

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#296]
Actuellement, le CERFA pré-rempli contient les infos saisies en vert.
Souhaité : remplacer le vert par le bleu (attention, le bleu doit ressortir correctement à l'impression).

**Comment by ClemLan** [comment]
<img width="205" alt="Capture d’écran 2022-02-09 à 11 13 49" src="https://user-images.githubusercontent.com/73469494/153177565-fe1ccc6f-ed20-4c38-af0b-fc6a3acc2850.png">

après avoir consulté le DSFR, je peux vous conseiller ce bleu "info-425" #0063CB

**Comment by antoinebigard** [comment]
@pabloHry 👆
