### ISSUE TITLE
Ouverture d'un dossier au statut "en attente d'action" impossible (écran blanc)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#303]
Je sélectionne un dossier "en attente d'action" de ma liste de dossiers (test non réalisé sur d'autres statuts).
J'arrive sur un écran blanc.
Je fais précédent sur le navigateur, le slug change mais j'ai toujours un écran blanc.

**Comment by antoinebigard** [comment]
nouveau dossier ?

**Comment by Anne-Camille** [comment]
Non, un ancien dossier que je voulais réouvrir (pas pu, blocage partout).

**Comment by antoinebigard** [comment]
Attention depuis la modif de Majorité les models à changer.

Pour information et te rassurer : un fois en prod et running ces cas n'arriveront plus car je ferais ce qu'on appelle des "script de migration" . Avec le rush jai pas le temps

**Comment by Anne-Camille** [comment]
ok je trash la card
