### ISSUE TITLE
R&D Ouvrir la possibilité à l'utilisateur de télécharger le CERFA en l'état à tout moment

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#349]
Définir sur le [workflow cible V2](https://whimsical.com/circuit-cerfa-demat-VNuawzFgha44utqYguBEty) où on peut télécharger en l'état

**Comment by ClemLan** [comment]
Première proposition : permettre le téléchargement directement à partir du tableau "Mes dossiers" (en actions cachées)

**Comment by antoinebigard** [comment]
+ sticky nope ?

**Comment by ClemLan** [comment]
nope : on ne tient pas forcément à renforcer ce comportement, sans pour autant l'exclure. 
Nous l'avons observé explicitement chez un utilisateur (avec un parcours justifié par des soucis que nous espérons résoudre via la plateforme). Si ce comportement s'avérait généralisé nous pourrions le remonter au premier plan mais pas utile pour l'instant.

**Comment by Anne-Camille** [comment]
@antoinebigard sticky en V1, mais R&D du sujet à prévoir en V2 (des tests utilisateurs avec le sticky permettront de qualifier ce qui est mieux à faire : on pourrait aussi proposer cette fonction directement dans les actions du dossier au niveau de la liste des dossiers => aujurd'hui on a juste l'action supprimer, demain on pourrait avoir télécharger, créer un avenant, créer un contrat successif, partager, ...)

**Comment by Anne-Camille** [comment]
@ClemLan j'ai alimenté le workflow V2 avec les endroits où le téléchargement sera possible : j'ai limité cette possibilité sur le parcours signature électronique pour engager l'utilisateur vers le parcours papier (sinon on perd sa trace).
Je mets donc cette carte en terminé.
