### ISSUE TITLE
Page génération du cerfa : retirer les différentes étapes car télétransmission possible

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#369]
Changer texte étape 2 par :
2. Cliquez sur Télétransmettre ; le contrat et ses éventuelles pièces jointes seront transmis à  [DDETS du Val d'Oise mail]

**Comment by antoinebigard** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/6003532/154917295-7e1822e7-21ea-448c-afdf-9138fedeef02.png">

-----

Ce dossier est finalisé, toute modification devra faire l'objet d'un avenant.

Vos prochaines étapes :

Imprimez le document pour signatures
Envoyez le document signé à l'adresse suivante DDETSPP de Corse-du-Sud ddetspp-certification@corse-du-sud.gouv.fr
Suivez l'avancement de votre dossier depuis votre espace
Pour toute question, consultez [la page "Assistance"](http://localhost/assistance)

**Comment by antoinebigard** [comment]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/6003532/154917486-8c9a2c91-e8da-401a-97ce-d0419659731b.png">
