### ISSUE TITLE
mailing Employeurs testeurs

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#381]
- [x] rédiger email =>@Anne-Camille
- [x] go à voir avec @antoinebigard  sur contenu
- [x] envoyer email aux interviewés cet été + testeurs récents => @ClemLan 

Madame, Monsieur, 

Vous avez été interviewé(e) l'été dernier et/ou testeur(euse) de la nouvelle plateforme de saisie en ligne des contrats d'apprentissage pour les employeurs publics et nous vous en remercions. 

Nous sommes heureux de vous informer que vous pouvez désormais saisir et télétransmettre vos contrats d'apprentissage sur https://contrat.apprentissage.beta.gouv.fr/  

Comme vous pourrez le constater, certaines de vos remarques et suggestions ont déjà été prises en compte ; les autres seront développées en amélioration continue et intégrées progressivement. Cette version beta est d'ores et déjà opérationnelle dans ses fonctionnalités principales :

- un maximum de champs préremplis de façon automatique ;
- des contrôles de format et de cohérence des données renseignées ;
- le partage du dossier pour que chaque contributeur puisse le compléter et/ou le signer ;
- la transmission du document et des pièces jointes à votre DREETS.

Prochainement (liste non exhaustive) :
- vous et l'ensemble des signataires aurez également la possibilité de signer électroniquement ;
- le tableau de suivi des dossiers sera amélioré ; 
- une fonction de recherche vous permettra de retrouver facilement un dossier dans la liste ;
- des champs commentaires pour informer les contributeurs ou contacter l'assistance.

Des opérations de communication auront lieu autour de la plateforme à la fin du mois (newsletter, mailings, articles web, liens sur les sites consultés par les employeurs publics, posts sur les réseaux sociaux, ...). Vous pouvez d'ores et déjà consulter [la vidéo de promotion du service.](https://dai.ly/x87z75c)

Si vous avez des contrats ou avenants à saisir et transmettre maintenant ou dans les jours qui viennent, utilisez (https://contrat.apprentissage.beta.gouv.fr/) et faites-nous part de votre expérience.

Merci de votre contribution à la construction de ce service, 

L'équipe Contrat d'apprentissage dématérialisé pour la fonction publique.

**Comment by ClemLan** [comment]
@Anne-Camille fait!
