### ISSUE TITLE
Wording des messages de validation

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#409]
- [ ] dans fichier excel, définir quels champs doivent avoir un message de validation
- [ ] wording du message de validation

**Comment by ClemLan** [comment]
@Anne-Camille Sauf erreur de ma part, pas d'autres messages de validation sur le formulaire que les SIRET

**Comment by Anne-Camille** [comment]
@ClemLan ok si tu estimes qu'il n'y a pas d'autres endroits que les siret ou il faut un message de validation, alors c'est bon?

**Comment by ClemLan** [comment]
ça devrait !

**Comment by Anne-Camille** [comment]
@ClemLan please serait-il possible de le préciser dans la maquette des états ? comme ça je ne créé pas de 2e carte !

**Comment by ClemLan** [comment]
@Anne-Camille done
