### ISSUE TITLE
Retirer bloc info "Lieu de formation" : info erronée qui induit en erreur

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#420]

**Comment by antoinebigard** [comment]
?????

**Comment by Anne-Camille** [comment]
![image](https://user-images.githubusercontent.com/63646363/154964480-f92210c1-c55e-403d-9ea1-76eab2cc075b.png)

Justement : le lieu de formation peut être différent du lieu de gestionnaire ! Le Bloc d'info semble affirmer le contraire, d'où proposition de le retirer.
