### ISSUE TITLE
Accès impossible après création de compte

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#439]
Pb remonté par l'utilisateur :  
Nous nous sommes connectées à la plateforme, nous avons bien créé un compte mais il nous est impossible d’accéder à un dossier pour le compléter car la page disparaît.
Nous avons essayé avec  Internet explorer, firefox et mozilla, sans succès.

**Comment by antoinebigard** [comment]
Elle est finie celle-ci non ?

**Comment by Anne-Camille** [comment]
il me semble oui ! Je te laisse la déplacer du coup ?
