### ISSUE TITLE
Revoir page connexion cf employeurs qui s'attendent à recevoir des codes en auto

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#441]

**Comment by ClemLan** [comment]
Proposition non-alignée : https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=866%3A90592

Proposition alignée : https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=871%3A90852
