### ISSUE TITLE
[Abandon] Fin de parcours : rendre plus explicite le fait que le dossier est bien télétransmis, indiquer les étapes suivantes

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#450]
En tant qu'utilisateur, lorsque je clique sur télétransmettre, il ne se passe rien d'explicite. Le bouton disparaît et il ne reste que le bouton "téélcharger sans signature". Je ne sais pas ce qu'il faut que je fasse ensuite.

Souhaité : rendre très explicite le fait que le dossier a été télétransmis et que les signatures ne sont pas nécessaires pour l'instruction du dossier, reporter ensuite les étapes à réaliser. (possible de mettre un faux bouton avec une anim qui indique "en cours de télétransmission).

Traité avec nouveau workflow

**Comment by ClemLan** [comment]
@Anne-Camille  résolu avec le nouveau parcours
