### ISSUE TITLE
Wording étapes à harmoniser (signatures et post-signatures)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#453]
**Actuel**
_Choix Signature :_ 

Téléchargez le document complété
Imprimez le contrat
Recueillez les différentes signatures
Transmission automatique à votre DEETS

_Télétransmis:_

![image](https://user-images.githubusercontent.com/63646363/156551229-ab4c0514-5d94-484f-93b4-6d35f83c110a.png)

**Souhaité**

Harmoniser les textes, rendre très explicite que le doc est télétransmis 
Workflow [cible V2](https://whimsical.com/circuit-cerfa-demat-VNuawzFgha44utqYguBEty)

**Comment by ClemLan** [comment]
Avec le parcours revu : 
Confirmation par modale : [Lien Figma](https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=984%3A145651)
Pour aller vite : [Lien Figma](https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=1007%3A91781)

**Comment by Anne-Camille** [comment]
@ClemLan J'imaginais plus un truc comme ça : 
![image](https://user-images.githubusercontent.com/63646363/158364994-dcefd61d-5229-46ae-8654-5443d2227e71.png)

![image](https://user-images.githubusercontent.com/63646363/158367215-6fb07428-d3ad-42b4-a596-9672a142a4a9.png)


![image](https://user-images.githubusercontent.com/63646363/158367248-2d825c4f-f6f7-4703-aca0-33c1174e5b41.png)


![image](https://user-images.githubusercontent.com/63646363/158367288-401c3cf2-adda-4c76-9dab-cc4fdfa2afc3.png)

**Comment by ClemLan** [comment]
@Anne-Camille Ah ben oui si on peut changer des écrans ok ^^ je vous fais ça jeudi
