### ISSUE TITLE
Ajouter info erreur transmission Agecap dans Metabase

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#469]
info erreur de télétransmission dans MB. Ajout dans la collection "dossiers" (avec le message d'erreur en clair).

Besoin = passation => accès à l'alerting en cas de nok api retour agecap ailleurs que dans slack

**Comment by antoinebigard** [comment]
comment veut-on que ça apparaisse ?
cad: 
L’état courant ou tous les précédents états ? Sachant que la "question" metabase sera vraiment plus complexe si c'est un historique
