### ISSUE TITLE
Ready to dev : page de connexion (mise en avant bloc 1ère connexion) + rééquilibrage 2 modes de connexion

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#473]
suite passation, décision DGEFP de ne conserver qu'un seul mode de connexion : PDS

- [ ] version courante améliorée : [(V0 avec maintien des 2 modes de connexion)](https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=1341%3A118065)
- [ ] revoir le parcours utilisateur pour ne proposer que la créa de compte via PDS  : ([V1 moins disante](https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=1206%3A99426)
- [ ] atelier pour V2 mieux intégrée (connexion pds en iframe ? widget ?...)
- [ ] à la migration, prévoir une com aux utilisateurs natifs pour les informer de la nécessité de créer un nouveau mdp (PI carte migration https://github.com/mission-apprentissage/cerfa/issues/526)

https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=866%3A90592

Supprimer la création de compte native => @ClemLan pourrais-tu ajuster les maquettes avec cette demande stp ?

Weekly du 01/04 : demande de migration des connexions natives vers PDS

**Comment by ClemLan** [comment]
[Nouveau parcours](https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=1206%3A99420), avec conservation des maquettes proposées initialement.

**Comment by ClemLan** [comment]
Suite à discussion DGEFP : [flow avec la double connexion](https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=1341%3A118065)
