### ISSUE TITLE
Durcissement du mot de passe : passage de 8 à 12 caractères

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#488]
**Origine du besoin**
Suite ebios, renforcement de la sécurité

A deployer en même temps que https://github.com/mission-apprentissage/cerfa/issues/485

- [x] passage de 8 à 12 car sur stock+flux
- [ ] informer les utilisateurs-stock du motif de la demande de re-création de mdp dans un bandeau d'info
- [ ] informer assistance de ce que vont recevoir les utilisateurs-stock

**Comment by antoinebigard** [comment]
https://cdn.zappy.app/88ac841e7829e9313adb038b8badbc7f.gif

**Comment by Anne-Camille** [comment]
**Recette**

- [ ] réinitialisation mdp Origin : OK
- [ ] création de compte Origin : OK
- [ ] reconnexion compte Origin suite création : KO => 
1. je renseigne mon mdp suite email reçu (note : l'email n'existe pas c'est peut être ce qui explique la suite)
2. je vais sur la plateforme de connexion et renseigne mes éléments :écran bloqué sur message d'erreur (id et mdp invalides)
3. reclic sur connexion : rien ne se passe, écran tjs bloqué avec message d'erreur
4. clic sur "créer un compte" : apparition du message "merci pour votre inscription", mais tjs impossible d'accéder au compte
5. finalement je retourne sur l'email, je recommence la saisie d'un nouveau mdp et tout se passe bien.

- [ ] création compte PDS n'exige pas 12 caractères : 
![image](https://user-images.githubusercontent.com/63646363/158792694-a7f9bdcb-6d67-45ae-83a4-0179952404b6.png)
- [ ] connexion compte
