### ISSUE TITLE
Création de compte : ressaisie du siret impossible en cas d'erreur dans la première saisie

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#495]
1. Je renseigne un siret invalide lors de la création de compte
2. j'ai le message "siret n'existe pas'
3. je corrige le siret dans le champ => impossible de cliquer sur suivant, même après avoir fait "entrée"
4. j'efface complètement le siret dans le champ et le recolle => impossible de cliquer sur suivant, même après avoir fait "entrée"
![image](https://user-images.githubusercontent.com/63646363/158792073-9270c38a-8dbd-44bf-8b59-b66672ee02a4.png)
5. Seule possibilité : ressaisir manuellement tous les chiffres pour lancer l'appel API.

**Comment by JulienBurgade** [comment]
AD MIA décommissionné, ticket abandonné
