### ISSUE TITLE
[Ready to dev] Mettre en place la nouvelle mire de connexion

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#502]
@ClemLan tu px mettre le lien vers le nouveau parcours de connexion steup ? Merciii

Abandon suite weekly du 01/04 : migration de tous les comptes natifs vers PDS attendue pour fin juillet

**Comment by antoinebigard** [comment]
![image](https://user-images.githubusercontent.com/6003532/159865731-cf14e71f-ba2d-4319-a309-db08e7768caf.png)
👆  est-ce que ça répond vraiment au besoin ?

**Comment by ClemLan** [comment]
@Anne-Camille @antoinebigard nouveau lien vers le nouveau parcours:  https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=1206%3A99426
