### ISSUE TITLE
Modification des états des champs

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#551]
Champs OK : 
- [ ] retrait du liseré vert
- [ ] retrait de l'icone check 

Champs NOK : 
- [ ] maintien du liseré rouge
- [ ] retrait de l'icone croix
- [ ] maintien du message d'erreur en rouge

Champs Verrouillés : 
- [ ] champ disabled
- [ ] maintien du cadenas
- [ ] si chevron dans l'input, le cadenas recouvre le chevron

Spinner : 
- [ ] retrait du spinner de l'input
- [ ] petit spinner au niveau de la mention “SAUVEGARDE AUTOMATIQUE ACTIVÉE” + check quand c’est save

@ClemLan : on n'a pas arbitré sur le spinner dans l'input ; que fait-on à ton avis ? maintien ? retrait ?...sachant qu'on a une carte en BL sur la mise en visibilité de l'enregistrement automatique.

**Comment by ClemLan** [comment]
Pour rappel : [les différents états des champs](https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=1215%3A99991)
