### ISSUE TITLE
Revoir wording des emails envoyés par Yousign (invitation à signer, code authentification, ...)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#606]
Actuellement : les contenus des emails adressés par Yousign sont des contenus par défaut ; 
Souhaité : personnaliser les contenus des différents emails adressés par Yousign.

Lien avec https://github.com/mission-apprentissage/cerfa/issues/599

**Comment by houssinegart** [comment]
le contenu des emails sur SharePoint  : https://ecu.collab.social.gouv.fr/dir/DGEFP/MISI/equipe/mia/_layouts/15/WopiFrame.aspx?sourcedoc=/dir/DGEFP/MISI/equipe/mia/Documents%20partages%20MIA/6.%20Conception/Notifications%20email%20de%20signature%20.docx&action=default
