### ISSUE TITLE
Téléphone : ajouter indicateurs manquants DROM COM

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#746]
![Image](https://user-images.githubusercontent.com/63646363/169782357-8628d0ce-7a8b-47e9-b018-6d4a17a91edc.png)

Mayotte +262
Guyane française, Nvelle Calédonie = OK
Guadeloupe +590
Martinique +596
Réunion +262
St Pierre et Miquelon +508
Polynésie +689
Wallis et Futuna +681

**Comment by antoinebigard** [comment]
- [ ] Réunion +262

- [ ] Guadeloupe +590
- [ ] Martinique +596
- [ ] Polynésie +689
- [ ] Guyane française, Nvelle Calédonie +594
- [ ] Polynésie +689

- [ ] St Pierre et Miquelon +508
- [ ] Wallis et Futuna +681

**Comment by antoinebigard** [comment]
Ok pour les codes territoires.

En revanche, Agecap ne peut recevoir que 13 caractères max ce qui est bloquant aujourd’hui
