### ISSUE TITLE
Déblocage contrat non télétransmis + rédaction procédure pour pouvoir traiter les pbs identiques

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#779]
**Origine du besoin**
Suite échec de télétransmission repéré dans l'alerting, Il est parfois nécessaire que l'admin fasse une modif pour télétransmettre à nouveau le dossier.

**To do**

- [ ] corriger le pb rencontré par ce dossier : https://assistance.emploi.gouv.fr/jira/browse/PLATDIG-135?filter=10669 : mise à jour du numéro de contrat , il y avait une erreur de frappe . Le bon numéro de contrat est : 083202110063525
- [ ] rédiger un process (dans Notion ?)  pour expliquer comment un Admin doit procéder pour résoudre les cas similaires

**Comment by antoinebigard** [comment]
- [ ] ajout d'une page administrateur afin de s'ajouter sur un dossier 
- [ ] Une fois ajouté sur un dossier un Administrateur a accès au bouton "Dépublié"

**Comment by antoinebigard** [comment]
Le process est donc : 
0- Etre admin
1. S’ajouter sur un dossier
2. Et donc voir le bouton “Dépublier”
