### ISSUE TITLE
Corriger le contrat v1 (avant le choix du mode de signature)

### ISSUE THREAD

**Issue by houssinegart** [mission-apprentissage/cerfa#817]
Permettre la correction du contrat tant que le mode de signature n'a pas été choisi.
La Popin de confirmation "Souhaitez-vous finaliser ce dossier" ne serait plus utile -> à supprimer
Une fois le mode de signature sélectionné, le contrat devient non éditable.
Dans l'écran du choix de mode de signature, ajouter un wording pour préciser à l'utilisateur que lorsque mode de signature sélectionné, le contrat devient non éditable.
Renommer le bouton "Finaliser et télécharger le dossier" en "Passer à l'étape suivante".

**Comment by JulienBurgade** [comment]
Quickwin : ajouter un bouton "Corriger" jusqu'au choix du mode de signature.
--> la présente carte est transformée en ce sens.

La correction d'un contrat après le choix du mode de signature a plus d'impacts et nécessite une analyse plus approfondie. -> création d'une carte dédiée.

**Comment by JulienBurgade** [comment]
Abandonné, remplacé par la carte 832
