### ISSUE TITLE
BUG - le bouton "non continuer l'édition" bloque le contrat

### ISSUE THREAD

**Issue by houssinegart** [mission-apprentissage/cerfa#821]
lorsque l'utilisateur clique sur le bouton "non continuer l'édition", le cotnrat passe au statut" signature en cours et il n'est plus éditable. il est sensé être éditable 

voir vidéo envoyée le 27/06 par email

**Comment by JulienBurgade** [comment]
Plus d'actualité car la popin sera supprimée.
