### ISSUE TITLE
BUG bloc rémunération ne calcule pas correctement les périodes

### ISSUE THREAD

**Issue by houssinegart** [mission-apprentissage/cerfa#841]
les périodes de rémunérations ne sont pas recalculées lorsque la date de naissance est mise à jour

dans l'exemple : l'apprenti est né le 04/09/2001

le contrat commence le 22/08/2022 et se termine le 30/09/2024

les périodes sont mal calculée, la première année je suis sensé avoir deux périodes :
une période du 22/08/2022 au 30/09/2022
puis uen deuxième période du 1/10/2022 au 03/09/2022

la plateforme me propose une seule période : 22/08/2022 au 21/08/2023

**Comment by houssinegart** [comment]
Référence du ticket : 232

**Comment by antoinebigard** [comment]
Le bug était dû au fait : 
Lors d'une anomalie précédente, nous avions vu que lorsque le "mois Fin de contrat" était égal "mois d'anniversaire" la dernière période de rémunération était mal calculée (elle dépassait d'un an). Nous avions donc ajouté une vérification. Mais cette vérification n'avait pas pris en compte ce cas. 

Maintenant la vérification est "mois Fin de contrat" était égal "mois d'anniversaire" + "Est-ce l'année de fin de contrat"

ce qui fix le bug et conserve le fix précèdent.

**Comment by houssinegart** [comment]
Bonjour Antoine, super merci beaucoup !

Le fix a été poussé en prod ou en recette ?

Houssine

De : Antoine Bigard ***@***.***>
Envoyé : vendredi 8 juillet 2022 10:33
À : mission-apprentissage/cerfa ***@***.***>
Cc : GARTOUM, Houssine (DGEFP) ***@***.***>; Author ***@***.***>
Objet : Re: [mission-apprentissage/cerfa] BUG bloc rémunération ne calcule pas correctement les périodes (Issue #841)


Le bug était dû au fait :
Lors d'une anomalie précédente, nous avions vu que lorsque le "mois Fin de contrat" était égal "mois d'anniversaire" la dernière période de rémunération était mal calculée (elle dépassait d'un an). Nous avions donc ajouté une vérification. Mais cette vérification n'avait pas pris en compte ce cas.

Maintenant la vérification est "mois Fin de contrat" était égal "mois d'anniversaire" + "Est-ce l'année de fin de contrat"

ce qui fix le bug et conserve le fix précèdent.
