### ISSUE TITLE
Tableau dossiers Mon espace (V0 sans Ui)  : Ajouter nom+ prénom apprenti + date exécution du contrat dans le libellé du dossier (lien avec fonction recherche)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/cerfa#99]
Actuellement un dossier s'intitule : 
Dossier [date] [heure]

Souhaité : dès que le champ "apprenti" est complété
Dossier [nom apprenti] [prénom apprenti] [date]
Siret entreprise
Date exécution du contrat
N° de télétransmission AGECAP (le wording devrait être "n° de dossier" avant le clic sur "télétransmettre")
maquette : https://www.figma.com/file/SxfbsW1nmwJsvwg66qqDhN/Cerfa?node-id=761%3A66866

La modif est visible sur : 

- [x] la liste des dossiers
- [x] l'intitulé du dossier en cours de complétion (pages formulaires)
- [x] le fil d'Ariane

V1 améliorée : https://github.com/mission-apprentissage/cerfa/issues/254

**Comment by ClemLan** [comment]
Lié à #254
